name = "TFAR Service and Supply Compat"
prefix = "sxp_tfar_service_supply_compat"
author = "Superxpdude"
files = [
	"mod.cpp",
	"README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

[header_exts]
version= "{{git \"id 8\"}}"